# ===========================
# Application Config
# ===========================
spring.application.name=movie-booking-backend
server.port=${PORT:8080}

# ===========================
# PostgreSQL Database Config
# ===========================
spring.datasource.url=jdbc:postgresql://dpg-d77oi9ggjchc73d2m5cg-a.oregon-postgres.render.com:5432/movie_db_h4mb
spring.datasource.username=movie_db_h4mb_user
spring.datasource.password=sFnnebcFSW7caEjmQIq4g66TAl2dKoVw

# ===========================
# JPA / Hibernate Config
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===========================
# JWT Config
# ===========================
# Must be at least 32 characters
jwt.secret=moviebooking_super_secret_key_must_be_32chars_min
jwt.expiration=86400000

# ===========================
# SQL Init
# ===========================
spring.sql.init.mode=never

# ===========================
# Jackson
# ===========================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

# ===========================
# Logging
# ===========================
logging.level.com.moviebooking=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG